### ISSUE TITLE
CSC : error CS8103: Combined length of user strings used by the program exceeds allowed limit. Try to decrease use of string literals.

### ISSUE THREAD

**Issue by Muru-solai** [dotnet/vscode-dotnet-runtime#570]
I had a MVC web application project built on .Net framework 4.5 and later I rewritten to DotNet core 3.1. Now I am migrating this project  from Core 3.1 to DotNet 6.  its vast project with multiple project within a single solution.  when I migrate from 3.1 to 6,  I done only few changes as followed

1. Changed target framework in .csproj file
2. upgrade all the package reference to latest version.
3. deprecated code is replaced

I am using VS Code to run the project , when compile the project getting following error.

_CSC : error CS8103: Combined length of user strings used by the program exceeds allowed limit. Try to decrease use of string literals. [D:\xxx\xxx.csproj]
    1047 Warning(s)
    1 Error(s)_ 

I referred few site and below suggested line of code I added in .csproj file inside <PropertyGroup> tag

 < RazorCompileOnBuild >false< /RazorCompileOnBuild > 
 < RazorCompileOnPublish >true< /RazorCompileOnPublish >

After adding the code, solution working perfectly without any error. however, is it right fix that I applied or is it due to number of warning(more than 1000) or anything else?

**Comment by nagilson** [comment]
I would recommend moving long strings into resource files. https://stackoverflow.com/questions/37193372/c-sharp-combined-length-of-user-strings-used-by-the-program-exceeds-allowed-limi


Also, this is the incorrect repo. I would direct further questions to the Razor SDK. Thanks!
